### ISSUE TITLE
what's the best way to use the outbox pattern w/ topics?

### ISSUE THREAD

**Issue by jswilley** [cfrenzel/Eventfully#11]
Hi.

I have been able to leverage the outbox pattern with queues.  What is the best way to get it working w/ topics?

**Comment by jswilley** [comment]
figured it out.  thanks

**Comment by cfrenzel** [comment]
For Azure Service Bus it is really just a matter of the connection string.  For the sender and receiver(s) the experience is the same for queues and subscriptions 👍
